site_name: MkDocs
site_url: https://github.com/danielnj21/mkdocs_test/
site_description: Project documentation with Markdown.
site_author: Daniel

repo_url: https://github.com/danielnj21/mkdocs_test/
edit_uri: blob/master/docs/

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
    - django

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide/
  - Developer Guide: dev-guide/
  - About:
    - Release Notes: about/release-notes.md
    - Contributing: about/contributing.md
    - License: about/license.md
