site_name: MkDocs
site_url: https://github.com/danielnj21/mkdocs_test/
site_description: Project documentation with Markdown.
site_author: Daniel

repo_url: https://github.com/danielnj21/mkdocs_test/
edit_uri: blob/master/docs/

theme:
  name: material

nav:
  - Home: README.md
  - TAB2: second_file.md
